import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  itGovernanceSidebar:      [{type: 'autogenerated', dirName: '01-it-governance'}],
  enterpriseArchSidebar:    [{type: 'autogenerated', dirName: '02-enterprise-architecture'}],
  legalComplianceSidebar:   [{type: 'autogenerated', dirName: '03-legal-compliance'}],
  softwareEngSidebar:       [{type: 'autogenerated', dirName: '04-software-engineering'}],
  infraOpsSidebar:          [{type: 'autogenerated', dirName: '05-infrastructure-operations'}],
  futureTechSidebar:        [{type: 'autogenerated', dirName: '06-future-technology'}],
  dataAiSidebar:            [{type: 'autogenerated', dirName: '07-data-ai-governance'}],
  securitySidebar:          [{type: 'autogenerated', dirName: '08-security-governance'}],
  qualitySidebar:           [{type: 'autogenerated', dirName: '09-quality-management'}],
  economicSidebar:          [{type: 'autogenerated', dirName: '10-economic-analysis'}],
  modernOrgSidebar:         [{type: 'autogenerated', dirName: '11-modern-organization'}],
};

export default sidebars;
