import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  governanceSidebar: [
    {type: 'autogenerated', dirName: '01-it-governance'},
    {type: 'autogenerated', dirName: '02-enterprise-architecture'},
    {type: 'autogenerated', dirName: '03-legal-compliance'},
  ],
  techSidebar: [
    {type: 'autogenerated', dirName: '04-software-engineering'},
    {type: 'autogenerated', dirName: '05-infrastructure-operations'},
    {type: 'autogenerated', dirName: '06-future-technology'},
  ],
  dataSecuritySidebar: [
    {type: 'autogenerated', dirName: '07-data-ai-governance'},
    {type: 'autogenerated', dirName: '08-security-governance'},
  ],
  managementSidebar: [
    {type: 'autogenerated', dirName: '09-quality-management'},
    {type: 'autogenerated', dirName: '10-economic-analysis'},
    {type: 'autogenerated', dirName: '11-modern-organization'},
  ],
};

export default sidebars;
